import { BlockType, CraftingRecipe, ItemDef } from '../types/game';

export const ITEM_REGISTRY: Record<string, ItemDef> = {
  // Blocks
  grass_block: {
    id: 'grass_block',
    name: 'Grass Block',
    type: 'block',
    blockId: BlockType.GRASS,
    iconColor: '#5b8c34',
    iconSymbol: '🟩',
    description: 'Fresh surface soil covered with verdant turf.',
    maxStack: 64,
  },
  dirt: {
    id: 'dirt',
    name: 'Dirt',
    type: 'block',
    blockId: BlockType.DIRT,
    iconColor: '#6f4e37',
    iconSymbol: '🟫',
    description: 'Rich fertile earth, easy to dig.',
    maxStack: 64,
  },
  stone: {
    id: 'stone',
    name: 'Stone',
    type: 'block',
    blockId: BlockType.STONE,
    iconColor: '#7a7a7a',
    iconSymbol: '⬜',
    description: 'Solid bedrock core of the world.',
    maxStack: 64,
  },
  cobblestone: {
    id: 'cobblestone',
    name: 'Cobblestone',
    type: 'block',
    blockId: BlockType.COBBLESTONE,
    iconColor: '#666666',
    iconSymbol: '🪨',
    description: 'Rough fractured stone suitable for building & tools.',
    maxStack: 64,
  },
  sand: {
    id: 'sand',
    name: 'Sand',
    type: 'block',
    blockId: BlockType.SAND,
    iconColor: '#d6c586',
    iconSymbol: '🟨',
    description: 'Fine grains found on beaches and riverbanks.',
    maxStack: 64,
  },
  wood_log: {
    id: 'wood_log',
    name: 'Wood Log',
    type: 'block',
    blockId: BlockType.WOOD,
    iconColor: '#5c3e21',
    iconSymbol: '🪵',
    description: 'Solid raw timber from trees. Essential for crafting.',
    maxStack: 64,
  },
  leaves: {
    id: 'leaves',
    name: 'Leaves',
    type: 'block',
    blockId: BlockType.LEAVES,
    iconColor: '#2d6a2d',
    iconSymbol: '🍃',
    description: 'Foliage canopy of woodland trees.',
    maxStack: 64,
  },
  planks: {
    id: 'planks',
    name: 'Wood Planks',
    type: 'block',
    blockId: BlockType.PLANKS,
    iconColor: '#966e40',
    iconSymbol: '📦',
    description: 'Refined lumber used for construction and basic tools.',
    maxStack: 64,
  },
  glass: {
    id: 'glass',
    name: 'Glass Block',
    type: 'block',
    blockId: BlockType.GLASS,
    iconColor: '#cbe7f5',
    iconSymbol: '🔲',
    description: 'Clear transparent pane to see outside while sheltered.',
    maxStack: 64,
  },
  bricks: {
    id: 'bricks',
    name: 'Clay Bricks',
    type: 'block',
    blockId: BlockType.BRICKS,
    iconColor: '#914232',
    iconSymbol: '🧱',
    description: 'Sturdy kiln-fired brick blocks for resilient shelters.',
    maxStack: 64,
  },
  stone_bricks: {
    id: 'stone_bricks',
    name: 'Stone Bricks',
    type: 'block',
    blockId: BlockType.STONE_BRICKS,
    iconColor: '#5e5e5e',
    iconSymbol: '🏛️',
    description: 'Carved masonry stone blocks with chiseled edges.',
    maxStack: 64,
  },
  crafting_bench: {
    id: 'crafting_bench',
    name: 'Crafting Bench',
    type: 'block',
    blockId: BlockType.CRAFTING_BENCH,
    iconColor: '#8a5c2d',
    iconSymbol: '🛠️',
    description: 'Workbench granting access to 3x3 advanced crafting.',
    maxStack: 64,
  },
  torch: {
    id: 'torch',
    name: 'Torch',
    type: 'block',
    blockId: BlockType.TORCH,
    iconColor: '#ffa834',
    iconSymbol: '🔥',
    description: 'Flickering warm torch to ward off shadow creatures.',
    maxStack: 64,
  },
  coal_ore: {
    id: 'coal_ore',
    name: 'Coal Ore',
    type: 'block',
    blockId: BlockType.COAL_ORE,
    iconColor: '#303030',
    iconSymbol: '⬛',
    description: 'Stone vein embedded with carbon coal chunks.',
    maxStack: 64,
  },
  iron_ore: {
    id: 'iron_ore',
    name: 'Iron Ore',
    type: 'block',
    blockId: BlockType.IRON_ORE,
    iconColor: '#a88f72',
    iconSymbol: '🔘',
    description: 'Mineral-rich ore containing metallic iron.',
    maxStack: 64,
  },
  gold_ore: {
    id: 'gold_ore',
    name: 'Gold Ore',
    type: 'block',
    blockId: BlockType.GOLD_ORE,
    iconColor: '#d6b333',
    iconSymbol: '🪙',
    description: 'Gleaming precious gold deposit buried deep.',
    maxStack: 64,
  },
  diamond_ore: {
    id: 'diamond_ore',
    name: 'Diamond Ore',
    type: 'block',
    blockId: BlockType.DIAMOND_ORE,
    iconColor: '#32c8c4',
    iconSymbol: '💎',
    description: 'Ultra-rare luminescent diamond crystals found at world depth.',
    maxStack: 64,
  },

  // Materials
  stick: {
    id: 'stick',
    name: 'Stick',
    type: 'material',
    iconColor: '#6f5031',
    iconSymbol: '🥢',
    description: 'Carved twig for handles, poles, and torches.',
    maxStack: 64,
  },
  coal: {
    id: 'coal',
    name: 'Coal',
    type: 'material',
    iconColor: '#222222',
    iconSymbol: '⚫',
    description: 'Flammable fuel mined from underground veins.',
    maxStack: 64,
  },
  iron_ingot: {
    id: 'iron_ingot',
    name: 'Iron Ingot',
    type: 'material',
    iconColor: '#cfd2d6',
    iconSymbol: '🔩',
    description: 'Smelted durable iron metal for advanced gear.',
    maxStack: 64,
  },
  gold_ingot: {
    id: 'gold_ingot',
    name: 'Gold Ingot',
    type: 'material',
    iconColor: '#f1c40f',
    iconSymbol: '🟡',
    description: 'Gleaming refined precious gold bar.',
    maxStack: 64,
  },
  diamond: {
    id: 'diamond',
    name: 'Diamond Crystal',
    type: 'material',
    iconColor: '#2bd9d6',
    iconSymbol: '🔷',
    description: 'Hardest crystal in the sandbox world.',
    maxStack: 64,
  },

  // Tools
  wooden_pickaxe: {
    id: 'wooden_pickaxe',
    name: 'Wooden Pickaxe',
    type: 'tool_pickaxe',
    iconColor: '#8a6538',
    iconSymbol: '⛏️',
    description: 'Rudimentary pickaxe to mine stone and coal.',
    maxStack: 1,
    miningSpeedMultiplier: 2.0,
    attackDamage: 2,
    tier: 'wood',
  },
  stone_pickaxe: {
    id: 'stone_pickaxe',
    name: 'Stone Pickaxe',
    type: 'tool_pickaxe',
    iconColor: '#757575',
    iconSymbol: '⛏️',
    description: 'Sturdier pickaxe capable of mining iron ore.',
    maxStack: 1,
    miningSpeedMultiplier: 3.5,
    attackDamage: 3,
    tier: 'stone',
  },
  iron_pickaxe: {
    id: 'iron_pickaxe',
    name: 'Iron Pickaxe',
    type: 'tool_pickaxe',
    iconColor: '#d6dadf',
    iconSymbol: '⛏️',
    description: 'Forged iron pickaxe that rapidly digs through all ores.',
    maxStack: 1,
    miningSpeedMultiplier: 5.5,
    attackDamage: 4,
    tier: 'iron',
  },
  diamond_pickaxe: {
    id: 'diamond_pickaxe',
    name: 'Diamond Pickaxe',
    type: 'tool_pickaxe',
    iconColor: '#00e5ff',
    iconSymbol: '⛏️',
    description: 'Ultimate crystalline mining tool with unmatched velocity.',
    maxStack: 1,
    miningSpeedMultiplier: 9.0,
    attackDamage: 6,
    tier: 'diamond',
  },
  wooden_sword: {
    id: 'wooden_sword',
    name: 'Wooden Sword',
    type: 'tool_sword',
    iconColor: '#8a6538',
    iconSymbol: '🗡️',
    description: 'Simple bladed weapon to defend against nocturnal monsters.',
    maxStack: 1,
    attackDamage: 4,
    tier: 'wood',
  },
  stone_sword: {
    id: 'stone_sword',
    name: 'Stone Sword',
    type: 'tool_sword',
    iconColor: '#757575',
    iconSymbol: '🗡️',
    description: 'Sharpened flint/stone blade with increased strike force.',
    maxStack: 1,
    attackDamage: 6,
    tier: 'stone',
  },
  iron_sword: {
    id: 'iron_sword',
    name: 'Iron Sword',
    type: 'tool_sword',
    iconColor: '#d6dadf',
    iconSymbol: '🗡️',
    description: 'Deadly steel-grade sword capable of fending off packs.',
    maxStack: 1,
    attackDamage: 8,
    tier: 'iron',
  },
  wooden_axe: {
    id: 'wooden_axe',
    name: 'Wooden Axe',
    type: 'tool_axe',
    iconColor: '#8a6538',
    iconSymbol: '🪓',
    description: 'Cuts down trees and wood logs twice as fast.',
    maxStack: 1,
    miningSpeedMultiplier: 2.5,
    attackDamage: 3,
    tier: 'wood',
  },
  stone_axe: {
    id: 'stone_axe',
    name: 'Stone Axe',
    type: 'tool_axe',
    iconColor: '#757575',
    iconSymbol: '🪓',
    description: 'Chipped stone hatchet that clears timber swiftly.',
    maxStack: 1,
    miningSpeedMultiplier: 4.0,
    attackDamage: 5,
    tier: 'stone',
  },
  wooden_shovel: {
    id: 'wooden_shovel',
    name: 'Wooden Shovel',
    type: 'tool_shovel',
    iconColor: '#8a6538',
    iconSymbol: '🥄',
    description: 'Excavates dirt, grass, and sand rapidly.',
    maxStack: 1,
    miningSpeedMultiplier: 2.5,
    attackDamage: 2,
    tier: 'wood',
  },

  // Food
  apple: {
    id: 'apple',
    name: 'Forest Apple',
    type: 'food',
    iconColor: '#e74c3c',
    iconSymbol: '🍎',
    description: 'Crisp juicy fruit harvested from foliage. Restores 4 hunger.',
    maxStack: 32,
    foodValue: 4,
  },
  berries: {
    id: 'berries',
    name: 'Sweet Berries',
    type: 'food',
    iconColor: '#9b59b6',
    iconSymbol: '🫐',
    description: 'Wild forest berries. Quick snack that restores 2 hunger.',
    maxStack: 64,
    foodValue: 2,
  },
  cooked_meat: {
    id: 'cooked_meat',
    name: 'Seared Ribs',
    type: 'food',
    iconColor: '#b03a2e',
    iconSymbol: '🍖',
    description: 'Nutritious roasted meat. Restores 8 hunger and heals health.',
    maxStack: 32,
    foodValue: 8,
  },
};

// Crafting Recipes
export const RECIPES: CraftingRecipe[] = [
  {
    id: 'planks_from_wood',
    name: 'Wood Planks (x4)',
    width: 1,
    height: 1,
    grid: ['wood_log'],
    output: { itemId: 'planks', count: 4 },
  },
  {
    id: 'sticks_from_planks',
    name: 'Sticks (x4)',
    width: 1,
    height: 2,
    grid: ['planks', 'planks'],
    output: { itemId: 'stick', count: 4 },
  },
  {
    id: 'crafting_bench_from_planks',
    name: 'Crafting Bench',
    width: 2,
    height: 2,
    grid: ['planks', 'planks', 'planks', 'planks'],
    output: { itemId: 'crafting_bench', count: 1 },
  },
  {
    id: 'torches_from_coal',
    name: 'Torches (x4)',
    width: 1,
    height: 2,
    grid: ['coal', 'stick'],
    output: { itemId: 'torch', count: 4 },
  },
  {
    id: 'wooden_pickaxe_recipe',
    name: 'Wooden Pickaxe',
    width: 3,
    height: 3,
    grid: [
      'planks', 'planks', 'planks',
      null, 'stick', null,
      null, 'stick', null
    ],
    output: { itemId: 'wooden_pickaxe', count: 1 },
  },
  {
    id: 'wooden_sword_recipe',
    name: 'Wooden Sword',
    width: 1,
    height: 3,
    grid: [
      'planks',
      'planks',
      'stick'
    ],
    output: { itemId: 'wooden_sword', count: 1 },
  },
  {
    id: 'wooden_axe_recipe',
    name: 'Wooden Axe',
    width: 2,
    height: 3,
    grid: [
      'planks', 'planks',
      'planks', 'stick',
      null, 'stick'
    ],
    output: { itemId: 'wooden_axe', count: 1 },
  },
  {
    id: 'wooden_shovel_recipe',
    name: 'Wooden Shovel',
    width: 1,
    height: 3,
    grid: [
      'planks',
      'stick',
      'stick'
    ],
    output: { itemId: 'wooden_shovel', count: 1 },
  },
  {
    id: 'stone_pickaxe_recipe',
    name: 'Stone Pickaxe',
    width: 3,
    height: 3,
    grid: [
      'cobblestone', 'cobblestone', 'cobblestone',
      null, 'stick', null,
      null, 'stick', null
    ],
    output: { itemId: 'stone_pickaxe', count: 1 },
  },
  {
    id: 'stone_sword_recipe',
    name: 'Stone Sword',
    width: 1,
    height: 3,
    grid: [
      'cobblestone',
      'cobblestone',
      'stick'
    ],
    output: { itemId: 'stone_sword', count: 1 },
  },
  {
    id: 'stone_axe_recipe',
    name: 'Stone Axe',
    width: 2,
    height: 3,
    grid: [
      'cobblestone', 'cobblestone',
      'cobblestone', 'stick',
      null, 'stick'
    ],
    output: { itemId: 'stone_axe', count: 1 },
  },
  {
    id: 'iron_ingot_from_ore',
    name: 'Iron Ingot (Smelt)',
    width: 1,
    height: 2,
    grid: ['iron_ore', 'coal'],
    output: { itemId: 'iron_ingot', count: 1 },
  },
  {
    id: 'iron_pickaxe_recipe',
    name: 'Iron Pickaxe',
    width: 3,
    height: 3,
    grid: [
      'iron_ingot', 'iron_ingot', 'iron_ingot',
      null, 'stick', null,
      null, 'stick', null
    ],
    output: { itemId: 'iron_pickaxe', count: 1 },
  },
  {
    id: 'iron_sword_recipe',
    name: 'Iron Sword',
    width: 1,
    height: 3,
    grid: [
      'iron_ingot',
      'iron_ingot',
      'stick'
    ],
    output: { itemId: 'iron_sword', count: 1 },
  },
  {
    id: 'diamond_pickaxe_recipe',
    name: 'Diamond Pickaxe',
    width: 3,
    height: 3,
    grid: [
      'diamond', 'diamond', 'diamond',
      null, 'stick', null,
      null, 'stick', null
    ],
    output: { itemId: 'diamond_pickaxe', count: 1 },
  },
  {
    id: 'glass_from_sand',
    name: 'Glass Block (x2)',
    width: 2,
    height: 2,
    grid: [
      'sand', 'sand',
      'sand', 'sand'
    ],
    output: { itemId: 'glass', count: 2 },
  },
  {
    id: 'bricks_from_dirt',
    name: 'Clay Bricks (x4)',
    width: 2,
    height: 2,
    grid: [
      'dirt', 'dirt',
      'dirt', 'dirt'
    ],
    output: { itemId: 'bricks', count: 4 },
  },
  {
    id: 'stone_bricks_from_cobble',
    name: 'Stone Bricks (x4)',
    width: 2,
    height: 2,
    grid: [
      'cobblestone', 'cobblestone',
      'cobblestone', 'cobblestone'
    ],
    output: { itemId: 'stone_bricks', count: 4 },
  },
];
